# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-27 07:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flickrstats', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DayStatistic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('ts_start', models.IntegerField()),
                ('ts_end', models.IntegerField()),
                ('date_retrieved', models.DateTimeField()),
            ],
        ),
        migrations.RenameModel(
            old_name='PhotoStats',
            new_name='PhotoStat',
        ),
        migrations.RemoveField(
            model_name='daystatistics',
            name='photos',
        ),
        migrations.RemoveField(
            model_name='photostat',
            name='daystatistics',
        ),
        migrations.DeleteModel(
            name='DayStatistics',
        ),
        migrations.AddField(
            model_name='daystatistic',
            name='photos',
            field=models.ManyToManyField(through='flickrstats.PhotoStat', to='flickrstats.Photo'),
        ),
        migrations.AddField(
            model_name='photostat',
            name='daystatistic',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='flickrstats.DayStatistic'),
            preserve_default=False,
        ),
    ]
