# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-28 04:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flickrstats', '0002_auto_20161227_0757'),
    ]

    operations = [
        migrations.AlterField(
            model_name='daystatistic',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='daystatistic',
            name='date_retrieved',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
