# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-28 19:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flickrstats', '0004_auto_20161228_0450'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
            ],
        ),
        migrations.AlterField(
            model_name='photo',
            name='date_taken',
            field=models.CharField(default='0', max_length=20),
        ),
        migrations.AlterField(
            model_name='photo',
            name='favorited_by',
            field=models.ManyToManyField(related_name='photos_favorited', through='flickrstats.Favorite', to='flickrstats.FlickrUser'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='title',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='photo',
            name='total_comments',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='photo',
            name='total_favorites',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='photo',
            name='total_views',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='comment',
            name='photo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flickrstats.Photo'),
        ),
        migrations.AddField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flickrstats.FlickrUser'),
        ),
        migrations.AddField(
            model_name='photo',
            name='commented_by',
            field=models.ManyToManyField(related_name='photos_commented', through='flickrstats.Comment', to='flickrstats.FlickrUser'),
        ),
    ]
