# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-05 22:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flickrstats', '0005_auto_20161228_1928'),
    ]

    operations = [
        migrations.AddField(
            model_name='daystatistic',
            name='completed',
            field=models.BooleanField(default=True),
        ),
    ]
